# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import robotenv_pb2 as robotenv__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in robotenv_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RobotEnvStub(object):
    """RobotEnv service manages robot hardware and provides control interface.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetObservationSpec = channel.unary_unary(
                '/robotenv.RobotEnv/GetObservationSpec',
                request_serializer=robotenv__pb2.GetObservationSpecRequest.SerializeToString,
                response_deserializer=robotenv__pb2.ObservationSpec.FromString,
                _registered_method=True)
        self.GetConfig = channel.unary_unary(
                '/robotenv.RobotEnv/GetConfig',
                request_serializer=robotenv__pb2.GetConfigRequest.SerializeToString,
                response_deserializer=robotenv__pb2.RobotConfig.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/robotenv.RobotEnv/Reset',
                request_serializer=robotenv__pb2.ResetRequest.SerializeToString,
                response_deserializer=robotenv__pb2.ResetResponse.FromString,
                _registered_method=True)
        self.Step = channel.unary_unary(
                '/robotenv.RobotEnv/Step',
                request_serializer=robotenv__pb2.StepRequest.SerializeToString,
                response_deserializer=robotenv__pb2.StepResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/robotenv.RobotEnv/HealthCheck',
                request_serializer=robotenv__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=robotenv__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.GetVersion = channel.unary_unary(
                '/robotenv.RobotEnv/GetVersion',
                request_serializer=robotenv__pb2.GetVersionRequest.SerializeToString,
                response_deserializer=robotenv__pb2.VersionInfo.FromString,
                _registered_method=True)


class RobotEnvServicer(object):
    """RobotEnv service manages robot hardware and provides control interface.
    """

    def GetObservationSpec(self, request, context):
        """GetObservationSpec returns the schema of observations this robot provides.
        Call this once at startup to understand what fields are available.

        Example: If robot provides joint_positions and cartesian_position,
        control loop knows it can use both for policy input.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfig(self, request, context):
        """GetConfig returns robot hardware configuration.
        Includes gripper type, frame type, degrees of freedom, etc.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Reset robot to initial state.
        Supports different reset modes: home, random, target position, or current.

        Returns initial observation after reset completes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Step(self, request, context):
        """Step executes one action and returns the resulting observation.
        This is a blocking call - returns when action is executed and fresh observation is ready.

        Action is provided in the specified action_space (e.g., cartesian_velocity, joint_position).
        Returns robot state observation after executing the action.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """HealthCheck verifies service is running and ready.
        Used for service discovery and readiness probes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVersion(self, request, context):
        """GetVersion returns the deployed code version info.
        Reads from version_info.txt generated during Ansible deployment.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotEnvServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetObservationSpec': grpc.unary_unary_rpc_method_handler(
                    servicer.GetObservationSpec,
                    request_deserializer=robotenv__pb2.GetObservationSpecRequest.FromString,
                    response_serializer=robotenv__pb2.ObservationSpec.SerializeToString,
            ),
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=robotenv__pb2.GetConfigRequest.FromString,
                    response_serializer=robotenv__pb2.RobotConfig.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=robotenv__pb2.ResetRequest.FromString,
                    response_serializer=robotenv__pb2.ResetResponse.SerializeToString,
            ),
            'Step': grpc.unary_unary_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=robotenv__pb2.StepRequest.FromString,
                    response_serializer=robotenv__pb2.StepResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=robotenv__pb2.HealthCheckRequest.FromString,
                    response_serializer=robotenv__pb2.HealthCheckResponse.SerializeToString,
            ),
            'GetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersion,
                    request_deserializer=robotenv__pb2.GetVersionRequest.FromString,
                    response_serializer=robotenv__pb2.VersionInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robotenv.RobotEnv', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('robotenv.RobotEnv', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RobotEnv(object):
    """RobotEnv service manages robot hardware and provides control interface.
    """

    @staticmethod
    def GetObservationSpec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robotenv.RobotEnv/GetObservationSpec',
            robotenv__pb2.GetObservationSpecRequest.SerializeToString,
            robotenv__pb2.ObservationSpec.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robotenv.RobotEnv/GetConfig',
            robotenv__pb2.GetConfigRequest.SerializeToString,
            robotenv__pb2.RobotConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robotenv.RobotEnv/Reset',
            robotenv__pb2.ResetRequest.SerializeToString,
            robotenv__pb2.ResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robotenv.RobotEnv/Step',
            robotenv__pb2.StepRequest.SerializeToString,
            robotenv__pb2.StepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robotenv.RobotEnv/HealthCheck',
            robotenv__pb2.HealthCheckRequest.SerializeToString,
            robotenv__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robotenv.RobotEnv/GetVersion',
            robotenv__pb2.GetVersionRequest.SerializeToString,
            robotenv__pb2.VersionInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
